### ISSUE TITLE
invalid token handling is incorrect

### ISSUE THREAD

**Issue by lifeiscontent** [sergiodxa/remix-auth-oauth2#115]
https://github.com/sergiodxa/remix-auth-oauth2/blob/1e911b096267bd093c0b857df084d3d5b3ed9625/src/lib/token.ts#L56-L67

when I have an expired token the result looks something like this:

```
OAuth2RequestResult {
  body: {
    error: 'invalid_token',
    error_description: 'Token expired or revoked'
  }
}
```

and I get an error saying ```Error: Missing or invalid 'error_uri' field```

**Comment by cjenaro** [comment]
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/24cab8f0-0268-425f-8bba-6c8d08791934">


I'm getting a similar issue when using X's oauth, I spent a while trying to figure out what the error was, it was getting overwritten with the error uri one
