### ISSUE TITLE
cookieSessionStorage does not clear sessionStateKey and sessionCodeVerifierKey after OAuth2 success

### ISSUE THREAD

**Issue by istarkov** [sergiodxa/remix-auth-oauth2#122]
### Title: `cookieSessionStorage` retains `sessionStateKey` _("oauth2:state")_ and `sessionCodeVerifierKey` _("oauth2:codeVerifier")_ indefinitely

**Description**:

There seems to be an issue with the `cookieSessionStorage` implementation where `sessionStateKey` _("oauth2:state")_ and `sessionCodeVerifierKey` _("oauth2:codeVerifier")_ are not removed as intended.

**Steps to Reproduce:**

1. When using `cookieSessionStorage`, the `sessionStateKey` _("oauth2:state")_ and `sessionCodeVerifierKey` _("oauth2:codeVerifier")_ should be cleared after a successful OAuth flow.
   
2. However, these keys are not cleared and persist in the session indefinitely. 

**Relevant Code:**

1. The code that unsets the session key: [Remix Auth OAuth2 - index.ts, Line 247](https://github.com/sergiodxa/remix-auth-oauth2/blob/fd2ee3c3093247fd9ed885693df86d686b14c95b/src/index.ts#L247)
   
2. On strategy success, the session is reread from the request, causing both keys to remain in the session: [Remix Auth - strategy.ts, Line 160](https://github.com/sergiodxa/remix-auth/blob/a2287ac1ec232c88206bf54f79b56b9596f75454/src/strategy.ts#L160)

**Expected Behavior:**

- After a successful OAuth2 flow, the `sessionStateKey` _("oauth2:state")_ and `sessionCodeVerifierKey` _("oauth2:codeVerifier")_ should be cleared from the session storage.

**Actual Behavior:**

- The session contains both keys forever, leading to unexpected behavior and potentially security concerns.

**Possible Solution:**

Somehow reuse session from authorisaztion call in sucess call.

**Comment by sergiodxa** [comment]
Latest version doesn't integrate directly with SessionStorage anymore so this is responsibility of the app now
