### ISSUE TITLE
revokeToken call failing with Invalid_client error

### ISSUE THREAD

**Issue by skondoji** [sergiodxa/remix-auth-oauth2#132]
Hi
I am using remix-oauth-oauth2 module version 2.4.0
When I manually call revoke url with all the required parameters, it is working fine. See the code below
```
const revokeUrl = `${COGNITO_USER_POOL_URL}/oauth2/revoke`;
        const response = await fetch(revokeUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            Authorization: `Basic ${btoa(`${COGNITO_APP_CLIENT_ID}:${COGNITO_APP_CLIENT_SECRET}`)}`
          },
          body: new URLSearchParams({
            token: refreshToken,
            token_type_hint: 'refresh_token'
          })
        });
```

However, when I am using  module's method   revokeToken(refreshToken,  {'tokenType': 'refresh_token' })
I am getting invalid_client error. The same startegy object successfully works for toekn endpoint for issuing tokens after authentication. This proves, all the values and urls to the OauthStrategy are correct including tokenRevocationEndpoint

    at Object.send (file://.............node_modules/remix-auth-oauth2/build/lib/token.js:82:23)
Any help here would be highly appreciated.

**Comment by skondoji** [comment]
I will open a new updated issue and closing this.

**Comment by jeremyforan** [comment]
@skondoji do you mind sharing some of your Cognito code. I am trying to implement it and running into some problems.
