### ISSUE TITLE
Logout flow is not clear. Login flow doesn't start after user is logged out.

### ISSUE THREAD

**Issue by skondoji** [sergiodxa/remix-auth-oauth2#134]
HI,
I am using remix-oauth-oauth2 module version 2.4.0 with AWS Cognito as service provider.

My logout functionality implementation:

1. Fetch  https://CognitoDomain/logout?client_id=1example23456789&logout_uri=https%3A%2F%2Fwww.example.com%2Fwelcome
2. Destroy the session and redirect the user  /home page
3. In the home page, we already have login to start the authentication flow.
4. In this authentication, we are not seeing the login form. Instead the user is being issued fresh Tokens and the user is successfully logged in.  My expectation was, after session is destroyed, when we call authenticate()  call, we need to see the login screen. That is not happening.

Questions:  

1. Is there an explicity logout support from this remix module?
2. Why login form is not displayed after we call authenticate() after logout and session destroyed.

**Comment by sergiodxa** [comment]
Since latest version, logout is out of scope of Remix Auth and the OAuth2Strategy
