### ISSUE TITLE
Example in readme seems to not working

### ISSUE THREAD

**Issue by 4FunAndProfit** [sergiodxa/remix-auth-oauth2#138]
Hello ! 

I just tried your library (thanks again for all your libraries for remix/RR7 it really is gold)

I have the following errors : 
- export let authenticator = new Authenticator<User>();
`Expected 1-2 arguments, but got 0.ts(2554)`
(seem to work if you put a cookie storage into () )
- On authenticator.use(
`Type 'OAuth2Strategy<User>' is missing the following properties from type 'Strategy<User, never>': failure, successts(2345)`

Can you please add a functional example in the readme? And for getUser how do you do it? It seems to use artic now so is it correct to use something like `const claims = decodeIdToken(tokens.idToken());` or does this library let us get claims directly?

Thanks a lot in advance!

**Comment by sergiodxa** [comment]
> And for getUser how do you do it? It seems to use artic now so is it correct to use something like const claims = decodeIdToken(tokens.idToken()); or does this library let us get claims directly?

The `getUser` is part is what's up to you, you could use the access token (`tokens.accessToken()` to fetch the user profile on the identity provider and then query the DB using the user id or email, or you could use `tokens.idToken()` (in case you used the scope `openid`) to get the data from there directly.

You could also use the tokens to fetch a separate API in case your app works as a backend for frontend (BFF), or you could just return the access token directly from the strategy verify function, and then store that in your session or cookie and use it directly in your loaders and actions.
