### ISSUE TITLE
Support for Arctic Providers

### ISSUE THREAD

**Issue by matamatanot** [sergiodxa/remix-auth-oauth2#141]
Since the release of v3, the internal implementation has started using Arctic. Arctic offers a wide range of [providers](https://github.com/pilcrowonpaper/arctic/tree/main/src/providers), but it is unclear whether these can be utilized in the current implementation. Clarification on the compatibility and support for these providers would be highly appreciated.

**Comment by sergiodxa** [comment]
This only uses the generic OAuth2 client, Arctic providers don't follow the same interface all the time (some have different arguments or methods), so it's not possible to support them all.
