### ISSUE TITLE
CodeChallengeMethod, Arctic/Oslo and general concerns

### ISSUE THREAD

**Issue by runjak** [sergiodxa/remix-auth-oauth2#146]
Hey 👋🙂,
looking at the changes from #137 a few things came to mind for me that I wanted to share in hopes that it is helpful.

## On CodeChallengeMethod

[The readme still states](https://github.com/sergiodxa/remix-auth-oauth2/blob/main/README.md?plain=1#L42) that one can configure `codeChallengeMethod: "S256"`, which in my understanding is not correct, because the setting is now using the enum from [arctic](https://npmjs.com/package/arctic), and is typed as `codeChallengeMethod?: CodeChallengeMethod;` instead.

Additionally `CodeChallengeMethod` is not being reexported by `remix-auth-oauth2`. This means users of the library will have to also install arctic as a dependency just to have access to the enum setting here, or they'll need to specify a value like `0` in the hopes that the enum remains stable.

This seems like a potential issue waiting to happen. As a user of this library it would be very nice, if I didn't need to drag in more dependencies so that I can use an enum essential for configuration without worrying about its stability. Generally as a developer something like `S256` or even `CodeChallengeMethod.S256` has a better DX and seems more reliable than putting a value of `0` or inventing a separate enum that has to be lined up.

## On arctic and oslo

In the past remix-auth-oauth2 had issues (#106, #107) with updating of [oslo](https://www.npmjs.com/package/oslo) dependencies. This did not necessarily inspire confidence in the project for me - even less when I noticed that the [oauth2 code over there](https://github.com/pilcrowonpaper/oslo/tree/main/src/oauth2) does not seem to have tests alongside.

I get that this seems nice from the perspective of reducing the amount of stuff to worry about in this repo, but it also makes the code harder to audit and brings more moving parts on board.

In #108 I was also wondering whether a native SHA256 implementation wouldn't be beneficial - before learning that it comes down to Cloudflares support of Buffers. If a developer could hand in their choice of hash function instead it'd not only remove a dependency but also spend less CPU time in non Cloudflare environments.

As an aside: reimplementation of these crypto primitives in JS and dependeing on them feels iffy to me - it strikes me as depending on code for cryptography that may not have had specialist reviews - even more so when dedicated code is available in [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto).

By building on arctic - which seems to currently [not be tagging](https://github.com/pilcrowonpaper/arctic/issues/203) their releases - there is at least [a test for JWT parsing now](https://github.com/pilcrowonpaper/arctic/blob/main/src/oidc.test.ts) - but it appears to me that the amount of untested code increases with it.

As a library `remix-auth-oauth2` now has even more moving parts and distance between itself and the actual authentication code. Less of this code seems to have tests alongside.

It also feels a bit funny to me that a library, which provides a strategy for an authentication library, uses itself a library that has multiple authentication providers to pick only one of them which is then again implemented in another library.

## General

A thing I like about remix-auth-oauth2 specifically is [how it has tests](https://github.com/sergiodxa/remix-auth-oauth2/blob/main/src/index.test.ts). It would feel quite nice to me to see more dependencies consolidated into this library again.

We've been working around #67, #144 on our end for some time now, which seems to be a pity - this strikes me as something where remix-auth-oauth2 is uniquely positioned - because of it's supposed aim for easy integration with remix. With recent changes it appears as developers we've got to care more about session storage than before. This makes things more explicit - which seems good - but I also wonder if it helps with the race between loaders or makes that harder, too.

---

I'm not sure which of these things are actionable, but hope this is somewhat interesting or helpful to learn. If you've got the time I'd love to learn more on background decisions and such.

**Comment by sergiodxa** [comment]
I re-exported the CodeChallengeMethod enum from Arctic so it can be used from this packages without installing other packages, I forgot to re-export it originally.

---

Related to the dependency on Arctic, now with Arctic this package has support for things I didn't considered originally like error handling on the callback, and a few other things I honestly didn't know about.

I also trust Pilcrow (author of Arctic and Lucia Auth) on his knowledge of OAuth2 and OIDC, in the worst case I think it should be possible to change the client without changing the interface of the strategy in the future if needed.

---

Related to the tests, even if Arctic doesn't have tests for everything, the `handles race condition of state and code verifier` tests in this package convert a complete happy-path OAuth2 and more tests could be added in the future here to ensure everything works and report issues to Arctic.

I'm ok with eventually moving to something else if needed, I just wanted to delegate part of the logic to a more specialized library so this can can focus on being used inside Remix Auth.

**Comment by runjak** [comment]
I see - thanks for the adjustment and taking the time to explain 🙏

**Comment by runjak** [comment]
Thanks for the explanation 🙏.

The situation of multiple authentication libraries organised in a chain of dependencies still strikes me as somewhat unnecessarily complex though. I still feel that it makes auditing the code harder and that the code in question becomes more complex because of it.

It's feels reassuring to hear that more tests may be considered and that there's an interest in making it easier to check which versions of Arctic and Oslo correspond to which npm packages.

On SHA-256: I'm fine with the reasoning. I don't think the hash function as is poses problem here. My remaining unease with it comes mostly from these points:

- Where possible I would prefer relying on standard interfaces like [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) over reimplementations. I feel that this generally aligns with an idea of embracing the platform we've got.
  - So far I've mostly heard the argument that Cloudflare doesn't support this. For such things a polyfill should usually do fine I imagine.
  - The argument of a simpler internal API thanks to synchronous code is interesting to hear. I'm not sure about my personal taste here, but I feel it's not important - because it's your code and you've already made a choice. It feels helpful to understand what motivated you to take it 🙂.
