### ISSUE TITLE
forEach is not a function

### ISSUE THREAD

**Issue by sbaleno** [sergiodxa/remix-auth-oauth2#149]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `remix-auth-oauth2@3.2.0` for the project I'm working on.

Getting an error with the latest code change on URLSearchParams(cookie.get(name)).entries().forEach

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/remix-auth-oauth2/build/lib/store.js b/node_modules/remix-auth-oauth2/build/lib/store.js
index d18d7e9..ee9e904 100644
--- a/node_modules/remix-auth-oauth2/build/lib/store.js
+++ b/node_modules/remix-auth-oauth2/build/lib/store.js
@@ -91,9 +91,9 @@ export class StateStore {
         for (let name of cookie.names()) {
             if (name.startsWith(cookieName)) {
                 // biome-ignore lint/complexity/noForEach: This is ok
-                new URLSearchParams(cookie.get(name))
-                    .entries()
-                    .forEach(([key, value]) => params.append(key, value));
+                for (const [key, value] of new URLSearchParams(cookie.get(name)).entries()) {
+                    params.append(key, value)
+                }
             }
         }
         return new StateStore(params);

```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by arabold** [comment]
Running into the exact same problem. Thanks for the patch 🙏 

> biome-ignore lint/complexity/noForEach: This is ok

Oh, the irony 🤣
