### ISSUE TITLE
Add proper logout

### ISSUE THREAD

**Issue by franzwilhelm** [sergiodxa/remix-auth-oauth2#15]
# Current usage

Right now I have to manually do the auth0 logout by doing a double redirect in my logout function:

```ts
export const loader: LoaderFunction = async ({ request }) => {
  return authenticator.logout(request, {
    redirectTo: `https://${appConfig.auth0.issuerBaseUrl}/v2/logout?client_id=${appConfig.auth0.clientId}&returnTo=${appConfig.auth0.baseUrl}/auth/login`,
  });
};
```

# Expected usage

```ts
export const loader: LoaderFunction = async ({ request }) => {
  return authenticator.logout(request, {
    redirectTo: `/auth/login`,
  });
};
```

**Comment by franzwilhelm** [comment]
Currently blocking on https://github.com/sergiodxa/remix-auth/discussions/125

**Comment by sergiodxa** [comment]
This is not something the OAuth2 strategy handle.


The logout method is not calling a function from the strategy, it just destroy the session.

If a strategy extending the OAuth2Strategy needs something else it should document it or expose a method you can call from the strategy itself.
