### ISSUE TITLE
Fix store to use cookieName

### ISSUE THREAD

**Issue by nowells** [sergiodxa/remix-auth-oauth2#150]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `remix-auth-oauth2@3.2.0` for the project I'm working on.

We set a different cookieName, and on oauth2 return, it was breaking as the callback did not use the cookieName.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/remix-auth-oauth2/build/index.js b/node_modules/remix-auth-oauth2/build/index.js
index 4a3ee82..7fca029 100644
--- a/node_modules/remix-auth-oauth2/build/index.js
+++ b/node_modules/remix-auth-oauth2/build/index.js
@@ -58,7 +58,7 @@ export class OAuth2Strategy extends Strategy {
         let code = url.searchParams.get("code");
         if (!code)
             throw new ReferenceError("Missing code in the URL");
-        let store = StateStore.fromRequest(request);
+        let store = StateStore.fromRequest(request, this.cookieName);
         if (!store.has()) {
             throw new ReferenceError("Missing state on cookie.");
         }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by oliver-wymer** [comment]
Had the same issue, this patch did fix it 👍
