### ISSUE TITLE
Support for custom authorization URL query parameters

### ISSUE THREAD

**Issue by AustinBrunkhorst** [sergiodxa/remix-auth-oauth2#3]
Auth0 supports [a few query parameters](https://auth0.com/docs/api/authentication#social) for the ability to customize the login flow. Notably `login_hint` for prefilling the username/email and `connection` for specifying the social connection (which saves the user a click).

I'm looking to add support for passing in these query parameters for the authorization URL for each call to `authenticator.authenticate()`. It seems like the only way to pass data to a `Strategy` without changing the interface would be via `options.context`.

I'm happy to make a PR for this but would like some input here in case I'm missing something or there's a better approach.

**Comment by sergiodxa** [comment]
This is supported now with #4. The way it works is that any search params in the URL of the request which triggered the redirect to the OAuth2 authorization URL is going to be added to the authorization URL of the provider.

In the Auth0 case, this means if you have the route `routes/login/auth0.tsx` which calls `authenticator.authenticate()` and you go to `/login/auth0?screen_hint=signup` it will pass the search param to Auth0.

The PR was released on [v1.2.0](https://github.com/sergiodxa/remix-auth-oauth2/releases/tag/v1.2.0) and I have personally used it successfully with the Remix Auth0Strategy, some other strategies may need code changes.
