### ISSUE TITLE
Support Basic authentication header

### ISSUE THREAD

**Issue by omlie** [sergiodxa/remix-auth-oauth2#35]
As per the [OAuth 2.0 Standard](https://www.rfc-editor.org/rfc/rfc6749#section-2.3.1) Section 2.3.1:

>The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a client password.

As far as I can tell, this is not supported in the OAuth 2.0 Strategy.

I can create a PR for you to look at!

**Comment by svengau** [comment]
Do you know when this PR will be merged ? thx

**Comment by omlie** [comment]
Does @sergiodxa have a minute to take a look at it?
