### ISSUE TITLE
Is refreshing taken care of by this library?

### ISSUE THREAD

**Issue by MoSattler** [sergiodxa/remix-auth-oauth2#37]
Is refreshing the token with a refresh token taken care of by this library, or is that something I need to take care off on the consumer side?

**Comment by sergiodxa** [comment]
It's outside the scope of Remix Auth and the different strategies, Remix Auth focus is to let you know who is the user, if you need the access tokens you need to take care of refreshing it yourself.

**Comment by sergiodxa** [comment]
You have full control of the session used, when you create an Authenticator instance you pass a sessionStorage object, use that same object to access the session from the cookie header and commit changes when you need.
