### ISSUE TITLE
Question about OAuth2Profile typings

### ISSUE THREAD

**Issue by hallowatcher** [sergiodxa/remix-auth-oauth2#41]
Hey, I had a question about OAuth2 profiles. Currently in this library, they are typed like this:

![image](https://user-images.githubusercontent.com/6265839/204392468-f843e825-c9bf-4f00-aa50-5d9fd013767d.png)
![image](https://user-images.githubusercontent.com/6265839/204392245-600c0b87-5ec4-4903-a0d1-0dfef1f93773.png)

This means that any type of profile I pass in must extend from that OAuth2Profile interface, even if it doesn't include all of those properties.

How can I type this to only be what the OAuth API provides?

**Comment by hallowatcher** [comment]
If you need an example, I made a full custom implementation of an OAuth strategy for `osu!`.

In the method for returning a profile from the API, I want to return the full API user instead of the one that extends OAuth2Profile, which like mentioned has properties that I will never need.

![image](https://user-images.githubusercontent.com/6265839/204393003-f1003cf1-03c9-40ee-ad41-0afb2658332a.png)

**Comment by sergiodxa** [comment]
From the OAuth2Profile the only required field is the `provider`, the rest are optional meaning you can add only what you need. But if you need something that the OAuth2Profile uses it would be ideal to return it, for example use displayName for the username.

The reason the OAuth2Profile exists is to allow strategy authors to normalize the data, if you install any OAuth2-based strategy you know the profile has an array of emails for example.

But if you're extending the OAuth2Strategy locally in your project feel free to return anything you need.
