### ISSUE TITLE
Feature request: make `fetchAccessToken` protected instead of private

### ISSUE THREAD

**Issue by dustinboss** [sergiodxa/remix-auth-oauth2#48]
Currently the `fetchAccessToken` method is `private`, but it would be helpful for extending the Strategy if it were `protected` instead.

My specific use case is using the `fetchAccessToken` method to rotate my tokens using a refresh token. That method currently supports the ability to rotate a refresh token, but because it's private, it's not accessible from any classes that are extending this strategy.

I can currently get around the `private` classification by using `@ts-ignore`, but I'd rather not be cheating.

Thanks for the great library!

**Comment by mr-menno** [comment]
Agreed. This would be useful.
