### ISSUE TITLE
`uuid` dependency or dev dependency?

### ISSUE THREAD

**Issue by lamplightdev** [sergiodxa/remix-auth-oauth2#69]
In the latest release `uuid` has been moved from `dependencies` to `devDependencies`. In environments that prune the dev dependencies this then causes an error on running the build:

```
Error: Cannot find module 'uuid'
```

So it looks like `uuid` should be moved back to `dependencies`?

**Comment by oswaldoacauan** [comment]
we are seeing the same issue, any updates @sergiodxa?

**Comment by sergiodxa** [comment]
Fix released on [v1.11.2](https://github.com/sergiodxa/remix-auth-oauth2/releases/tag/v1.11.2)
