### ISSUE TITLE
Unusable behind proxy

### ISSUE THREAD

**Issue by gabriel-le** [sergiodxa/remix-auth-oauth2#76]
The authentication process times out when the server is behind a proxy.

A possible fix would be to let developers override the fetch function and provide their own.

**Comment by sergiodxa** [comment]
It uses the global fetch function, so you could override it globally.

```ts
let originalFetch = globalThis.fetch;
globalThis.fetch = newFetchCompatibleWithProxy;
```

Also a `fetch` call only happens once in the code, here https://github.com/sergiodxa/remix-auth-oauth2/blob/593e397df11d3678fa4ad02935b44316ad2e5259/src/index.ts#L416-L420, and `fetchAccessToken` (the method where that happens) is marked as protected, so if you create a sub-class of OAuth2Strategy you could override `fetchAccessToken` to provide your own version using a fetch compatible with a proxy.

**Comment by gabriel-le** [comment]
Good to know, thanks for the tip!

**Comment by suzuki-shm** [comment]
I spent a considerable amount of time investigating this issue, so I’d like to share some of the difficulties I encountered:

First, I gave up on applying proxy settings exclusively to remix-auth-oauth2. I considered the following options:

1. I tried overriding the proxy settings on global.fetch in entry.server.ts, but this did not work.
2. Next, I suspected that the library’s internal fetch calls were not receiving the proxy settings correctly, so I attempted to use global-agent across the entire Remix application. However, this also failed.
3. Ultimately, I realized that Remix uses undici under the hood. By configuring EnvHttpProxyAgent from undici in app/entry.server.ts, I was finally able to reach the OAuth2.0 authentication provider I use.
However, once I deployed the application (running npm run build && npm start), this setup no longer worked. At that point, I switched back to global-agent, and it worked successfully in production.

Below is the relevant implementation of entry.server.ts:
```
/**
 * By default, Remix will handle generating the HTTP Response for you.
 * You are free to delete this file if you'd like to, but if you ever want it revealed again, you can run `npx remix reveal` ✨
 * For more information, see https://remix.run/file-conventions/entry.server
 */

// Read .env file settings
import dotenv from "dotenv";
dotenv.config();

// Use proxy agent for undici
import { EnvHttpProxyAgent, setGlobalDispatcher } from "undici";
const proxyAgent = new EnvHttpProxyAgent();
setGlobalDispatcher(proxyAgent);

// Use global-agent for production environment
import { bootstrap } from 'global-agent';
bootstrap();

// below is the default settings
import { PassThrough } from "node:stream";

import type { AppLoadContext, EntryContext } from "@remix-run/node";
import { createReadableStreamFromReadable } from "@remix-run/node";
...
```

I hope this helps anyone else who might run into similar issues.
