### ISSUE TITLE
Support query params for token request

### ISSUE THREAD

**Issue by kylekarpack** [sergiodxa/remix-auth-oauth2#8]
Hi, this is a bit of an odd situation, and I'm not sure how it should best be handled. I am dealing with an OAuth provider that requires all parameters for the token request to be sent as query parameters instead of body parameters. So for example, the provider requires that the token request look like this:
```bash
curl --location --request POST 'https://some-provider.com/oauth/authorize/?grant_type=authorization_code&redirect_uri=<param>&client_id=<param>&client_secret=<param>&code=<param>'
```
instead of the more standard version supported by this library:
```bash
curl --location --request POST 'https://some-provider.com/oauth/authorize/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=<param>' \
--data-urlencode 'redirect_uri=<param>' \
--data-urlencode 'client_id=<param>' \
--data-urlencode 'client_secret=<param>' \
--data-urlencode 'code=<param>'
```

I'm not sure if this is worth creating a setting for, or if I should just create a new strategy to handle this requirement. Creating a new strategy that extends this behavior isn't too hard:

```typescript
  async fetchAccessToken(
    code: string,
    params: URLSearchParams
  ) {
    // ...

    // Add all parameters as query parameters, as required by this provider
    const url = new URL(this.tokenURL);
    url.search = params.toString();
    let response = await fetch(url.toString(), { // This is what's different
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: params, // This isn't necessary
    });

  // ...
```

But the `fetchAccessToken` (https://github.com/sergiodxa/remix-auth-oauth2/blob/main/src/index.ts#L302) method is `private`, so it seems like it wasn't intented to be extended. I'm curious if that method could be made `protected`, or if this is a common enough scenario that it might be worth adding configuration to handle it. Please let me know if I can clarify anything or provide a PR to handle this situation.

**Comment by sergiodxa** [comment]
I'm not sure what provider is this but I'm sure the OAuth2 spec says to send that data in the body, and all provider I've seen so far uses that since it's better to don't send sensitive data (client secret) on the URL.

**Comment by kylekarpack** [comment]
Hi @sergiodxa, thanks for taking the time to review this. I see now that this is a non-standard OAuth pattern, so I'm probably on my own here.

It'd still be nice if the `fetchAccessToken` method could be `protected` instead of `private` to allow for overriding in custom strategies, but I understand if you'd prefer to not pollute the base library, in which case I can find another workaround. Thanks for the help!
