### ISSUE TITLE
Missing state on session

### ISSUE THREAD

**Issue by Fumaz** [sergiodxa/remix-auth-oauth2#86]
The state is set correctly in the browser's cookies (and decoding the cookie shows me the state is correct), but the server thinks it's not there.

**Comment by sergiodxa** [comment]
The error typically happens because either the session cookie was not set or the cookie was not sent from the browser (e.g. because of SameSite: Strict or the path config).

It's impossible to know exactly what's your issue without a replication repository to try it.
