### ISSUE TITLE
state value is not removed when cookie based session storage is used

### ISSUE THREAD

**Issue by gabriel-forro-bp** [sergiodxa/remix-auth-oauth2#90]
The value of the state parameter is not removed from the session after successful authentication when a cookie based session storage is used in the application. The state is unset in the [implementation](https://github.com/sergiodxa/remix-auth-oauth2/blob/090e78fd7aeb923fc152ce002f73feca262095af/src/index.ts#L204) but the new session is not committed in the response so the value stays in the session until the end of the validity of the session.
The session size is limited by the cookie size (4096 bytes) and therefore it would be nice to get rid of session values, which are useless.

**Comment by sergiodxa** [comment]
The new cookie used to keep the state is set to expire after 5 minutes by default, you can remove it yourself before, if you customize it it's up to the app to clear it or set a maxAge
